// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1TB9hNWx6r0ulC5EA4MWJqsoai5k7U48',
    appId: '1:429982705456:web:4c402140da4e5e0dcb8af5',
    messagingSenderId: '429982705456',
    projectId: 'aluga-comigo',
    authDomain: 'aluga-comigo.firebaseapp.com',
    storageBucket: 'aluga-comigo.appspot.com',
    measurementId: 'G-4WXLHS8H5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCc1f-Mq41oDdDkAu15SCAcVmiPzWe_KE',
    appId: '1:429982705456:android:370025498c399239cb8af5',
    messagingSenderId: '429982705456',
    projectId: 'aluga-comigo',
    storageBucket: 'aluga-comigo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcrkUb9bfIaeAn6EB5fJmvOIQgSOjEczM',
    appId: '1:429982705456:ios:ed012e6f6fb878e5cb8af5',
    messagingSenderId: '429982705456',
    projectId: 'aluga-comigo',
    storageBucket: 'aluga-comigo.appspot.com',
    iosBundleId: 'com.vittor.alugaComigo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcrkUb9bfIaeAn6EB5fJmvOIQgSOjEczM',
    appId: '1:429982705456:ios:97e5cc2b4ce7a7efcb8af5',
    messagingSenderId: '429982705456',
    projectId: 'aluga-comigo',
    storageBucket: 'aluga-comigo.appspot.com',
    iosBundleId: 'com.vittor.alugaComigo.RunnerTests',
  );
}
