name: aluga_comigo
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_modular: ^6.3.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  styled_text: ^8.1.0
  google_fonts: ^6.1.0
  animated_text_kit: ^4.2.2
  delayed_display: ^2.0.0
  gap: ^3.0.1
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  chiclet: ^1.1.0
  expandable_page_view: ^1.0.17
  just_the_tooltip: ^0.0.12
  flutter_snake_navigationbar: ^0.6.1
  responsive_framework: ^1.1.1
  velocity_x: ^4.1.2
  flip_card: ^0.7.0
  dartx: ^1.2.0
  story_view: ^0.16.5
  wave: ^0.2.2
  dismissible_page: ^1.0.2
  flutter_slider_drawer: ^2.1.3
  swipable_stack: ^2.0.0
  quickalert: ^1.0.2
  flutter_secure_storage: ^9.0.0
  freerasp: ^6.4.0
  skeletonizer: ^1.0.1
  alphabet_list_view: ^1.0.1
  card_swiper: ^3.0.1
  animated_stack: ^0.2.0
  flutter_bounce: ^1.1.0
  selector_wheel: ^1.1.2
  bubble: ^1.2.1
  octo_image: ^2.0.0
  flutter_isolate: ^2.0.4
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/fonts/google_fonts/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
